mod application_controller;
mod auth_controller;
mod forum_controller;
mod join_controller;
mod fallback_controller;
mod schoolarship_controller;
mod student_controller;
mod university_controller;
mod user_controller;
mod welcome_controller;

pub use application_controller::*;
pub use auth_controller::*;
pub use forum_controller::*;
pub use join_controller::*;
pub use fallback_controller::*;
pub use schoolarship_controller::*;
pub use student_controller::*;
pub use university_controller::*;
pub use user_controller::*;
pub use welcome_controller::*;