pub mod application;
pub mod auth;
pub mod forum;
pub mod join;
pub mod fallback;
pub mod schoolarship;
pub mod student;
pub mod university;
pub mod welcome;

pub use application::*;
pub use auth::*;
pub use forum::*;
pub use join::*;
pub use fallback::*;
pub use schoolarship::*;
pub use student::*;
pub use university::*;
pub use welcome::*;