pub mod application_controller;
pub mod auth_controller;
pub mod forum_controller;
pub mod fallback_controller;
pub mod scholarship_controller;
pub mod student_controller;
pub mod university_controller;
pub mod user_controller;
pub mod welcome_controller;

pub use application_controller::*;
pub use auth_controller::*;
pub use forum_controller::*;
pub use fallback_controller::*;
pub use scholarship_controller::*;
pub use student_controller::*;
pub use university_controller::*;
pub use user_controller::*;
pub use welcome_controller::*;